version: "3"
services:
  node:
    image: "node:18-alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    volumes:
      - .:/home/node/app
    ports:
      - 4173:4173
    command: sh -c "yarn install && yarn preview"
    stdin_open: true
    tty: true
